version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./credit_reports:/app/credit_reports
      - ./output_text:/app/output_text
    environment:
      - PYTHONPATH=/app
      - DEBUG=1
      - MAX_WORKERS=1  # For development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Enable auto-reload for development
